modus: TRAIN
dataset:
  name: data
  num_classes: 13
  data_path: ./dataset/raw/
  train_data_path: ./dataset/train/
  test_data_path: ./dataset/test/
  downsample_prefix: sample_0.03
labels:
  label_path: /classes/label_mapping.yaml
model:
  name: model
batch_generator:
  name: batch_generator
  params:
    batch_size: 1
train:
  epochs: 100
  batch_size: 2
  ckpt_dir: ./models/ckpts/
  ckpt_save_interval: 10
eval:
  batch_size: 2
SparseConv:
  in_channels: 3